---
server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vlsidlyarevich/spring-cloud-training
          search-paths: configs/lab9

management:
  security:
    enabled: false
